In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/emissions2022(CO2).csv')

In [ ]:
data

2022 Carbon Dioxide Emissions at Electric Power Plants  \
0                                            Plant Code       
1                                                     1       
2                                                     3       
3                                                     3       
4                                                     3       
...                                                 ...       
5290                                              99999       
5291                                              99999       
5292                                              99999       
5293  Notes:\nThe emissions data presented include t...       
5294  EIA Balancing Authority Regions are documented...       

                     Unnamed: 1 Unnamed: 2      Unnamed: 3   Unnamed: 4  \
0                    Plant Name      State    Sector Group  Sector Code   
1                    Sand Point         AK  ELECTRIC POWER            1   
2                         Barry         AL  ELECTRIC POWER            1   
3                         Barry         AL  ELECTRIC POWER            1   
4                         Barry         AL  ELECTRIC POWER            1   
...                         ...        ...             ...          ...   
5290  Estimate for Missing Data         WI      INDUSTRIAL            7   
5291  Estimate for Missing Data         WY  ELECTRIC POWER            1   
5292  Estimate for Missing Data         WY  ELECTRIC POWER            1   
5293                        NaN        NaN             NaN          NaN   
5294                        NaN        NaN             NaN          NaN   

       Unnamed: 5 Unnamed: 6             Unnamed: 7        Unnamed: 8  \
0     Prime Mover  Fuel Code  Aggregated Fuel Group  Generation (kWh)   
1              IC        DFO                    PET         2,903,000   
2              CA         NG                    GAS     2,817,683,000   
3              CT         NG                    GAS     5,336,143,000   
4              ST        BIT                   COAL     3,314,500,858   
...           ...        ...                    ...               ...   
5290           ST        RFO                    PET           343,852   
5291           ST        SUB                   COAL     1,738,032,266   
5292           ST        DFO                    PET         3,199,640   
5293          NaN        NaN                    NaN               NaN   
5294          NaN        NaN                    NaN               NaN   

                         Unnamed: 9  ...  \
0     Useful Thermal Output (MMBtu)  ...   
1                                 0  ...   
2                                 0  ...   
3                                 0  ...   
4                                 0  ...   
...                             ...  ...   
5290                          8,593  ...   
5291                              0  ...   
5292                              0  ...   
5293                            NaN  ...   
5294                            NaN  ...   

                                           Unnamed: 11  \
0     Fuel Consumption for Electric Generation (MMBtu)   
1                                               31,026   
2                                              805,220   
3                                           56,641,702   
4                                           33,612,334   
...                                                ...   
5290                                             1,790   
5291                                        20,742,815   
5292                                            38,062   
5293                                               NaN   
5294                                               NaN   

                                            Unnamed: 12  \
0     \n Fuel Consumption for Useful Thermal Output ...   
1                                                     0   
2                                                     0   
3       

In [ ]:

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
embedder = SentenceTransformer('distilbert-base-nli-stsb-mean-tokens')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [ ]:
data.dropna()

2022 Carbon Dioxide Emissions at Electric Power Plants  \
0                                            Plant Code       
2                                                     3       
3                                                     3       
4                                                     3       
5                                                     3       
...                                                 ...       
5288                                              99999       
5289                                              99999       
5290                                              99999       
5291                                              99999       
5292                                              99999       

                     Unnamed: 1 Unnamed: 2      Unnamed: 3   Unnamed: 4  \
0                    Plant Name      State    Sector Group  Sector Code   
2                         Barry         AL  ELECTRIC POWER            1   
3                         Barry         AL  ELECTRIC POWER            1   
4                         Barry         AL  ELECTRIC POWER            1   
5                         Barry         AL  ELECTRIC POWER            1   
...                         ...        ...             ...          ...   
5288  Estimate for Missing Data         WI      INDUSTRIAL            7   
5289  Estimate for Missing Data         WI      INDUSTRIAL            7   
5290  Estimate for Missing Data         WI      INDUSTRIAL            7   
5291  Estimate for Missing Data         WY  ELECTRIC POWER            1   
5292  Estimate for Missing Data         WY  ELECTRIC POWER            1   

       Unnamed: 5 Unnamed: 6             Unnamed: 7        Unnamed: 8  \
0     Prime Mover  Fuel Code  Aggregated Fuel Group  Generation (kWh)   
2              CA         NG                    GAS     2,817,683,000   
3              CT         NG                    GAS     5,336,143,000   
4              ST        BIT                   COAL     3,314,500,858   
5              ST         NG                    GAS       426,092,142   
...           ...        ...                    ...               ...   
5288           ST         NG                    GAS        34,336,114   
5289           ST        TDF                    MSW           210,989   
5290           ST        RFO                    PET           343,852   
5291           ST        SUB                   COAL     1,738,032,266   
5292           ST        DFO                    PET         3,199,640   

                         Unnamed: 9  ...  \
0     Useful Thermal Output (MMBtu)  ...   
2                                 0  ...   
3                                 0  ...   
4                                 0  ...   
5                                 0  ...   
...                             ...  ...   
5288                        909,027  ...   
5289                          4,370  ...   
5290                          8,593  ...   
5291                              0  ...   
5292                              0  ...   

                                           Unnamed: 11  \
0     Fuel Consumption for Electric Generation (MMBtu)   
2                                              805,220   
3                                           56,641,702   
4                                           33,612,334   
5                                            4,423,555   
...                                                ...   
5288                                           178,558   
5289                                             1,101   
5290                                             1,790   
5291                                        20,742,815   
5292                                            38,062   

                                            Unnamed: 12  \
0     \n Fuel Consumption for Useful Thermal Output ...   
2                                                     0   
3                                                     0   
4       

In [ ]:
data

2022 Carbon Dioxide Emissions at Electric Power Plants  \
0                                            Plant Code       
1                                                     1       
2                                                     3       
3                                                     3       
4                                                     3       
...                                                 ...       
5290                                              99999       
5291                                              99999       
5292                                              99999       
5293  Notes:\nThe emissions data presented include t...       
5294  EIA Balancing Authority Regions are documented...       

                     Unnamed: 1 Unnamed: 2      Unnamed: 3   Unnamed: 4  \
0                    Plant Name      State    Sector Group  Sector Code   
1                    Sand Point         AK  ELECTRIC POWER            1   
2                         Barry         AL  ELECTRIC POWER            1   
3                         Barry         AL  ELECTRIC POWER            1   
4                         Barry         AL  ELECTRIC POWER            1   
...                         ...        ...             ...          ...   
5290  Estimate for Missing Data         WI      INDUSTRIAL            7   
5291  Estimate for Missing Data         WY  ELECTRIC POWER            1   
5292  Estimate for Missing Data         WY  ELECTRIC POWER            1   
5293                        NaN        NaN             NaN          NaN   
5294                        NaN        NaN             NaN          NaN   

       Unnamed: 5 Unnamed: 6             Unnamed: 7        Unnamed: 8  \
0     Prime Mover  Fuel Code  Aggregated Fuel Group  Generation (kWh)   
1              IC        DFO                    PET         2,903,000   
2              CA         NG                    GAS     2,817,683,000   
3              CT         NG                    GAS     5,336,143,000   
4              ST        BIT                   COAL     3,314,500,858   
...           ...        ...                    ...               ...   
5290           ST        RFO                    PET           343,852   
5291           ST        SUB                   COAL     1,738,032,266   
5292           ST        DFO                    PET         3,199,640   
5293          NaN        NaN                    NaN               NaN   
5294          NaN        NaN                    NaN               NaN   

                         Unnamed: 9  ...  \
0     Useful Thermal Output (MMBtu)  ...   
1                                 0  ...   
2                                 0  ...   
3                                 0  ...   
4                                 0  ...   
...                             ...  ...   
5290                          8,593  ...   
5291                              0  ...   
5292                              0  ...   
5293                            NaN  ...   
5294                            NaN  ...   

                                           Unnamed: 11  \
0     Fuel Consumption for Electric Generation (MMBtu)   
1                                               31,026   
2                                              805,220   
3                                           56,641,702   
4                                           33,612,334   
...                                                ...   
5290                                             1,790   
5291                                        20,742,815   
5292                                            38,062   
5293                                               NaN   
5294                                               NaN   

                                            Unnamed: 12  \
0     \n Fuel Consumption for Useful Thermal Output ...   
1                                                     0   
2                                                     0   
3       

In [ ]:
data = data.dropna()

In [ ]:
data

2022 Carbon Dioxide Emissions at Electric Power Plants  \
0                                            Plant Code       
2                                                     3       
3                                                     3       
4                                                     3       
5                                                     3       
...                                                 ...       
5288                                              99999       
5289                                              99999       
5290                                              99999       
5291                                              99999       
5292                                              99999       

                     Unnamed: 1 Unnamed: 2      Unnamed: 3   Unnamed: 4  \
0                    Plant Name      State    Sector Group  Sector Code   
2                         Barry         AL  ELECTRIC POWER            1   
3                         Barry         AL  ELECTRIC POWER            1   
4                         Barry         AL  ELECTRIC POWER            1   
5                         Barry         AL  ELECTRIC POWER            1   
...                         ...        ...             ...          ...   
5288  Estimate for Missing Data         WI      INDUSTRIAL            7   
5289  Estimate for Missing Data         WI      INDUSTRIAL            7   
5290  Estimate for Missing Data         WI      INDUSTRIAL            7   
5291  Estimate for Missing Data         WY  ELECTRIC POWER            1   
5292  Estimate for Missing Data         WY  ELECTRIC POWER            1   

       Unnamed: 5 Unnamed: 6             Unnamed: 7        Unnamed: 8  \
0     Prime Mover  Fuel Code  Aggregated Fuel Group  Generation (kWh)   
2              CA         NG                    GAS     2,817,683,000   
3              CT         NG                    GAS     5,336,143,000   
4              ST        BIT                   COAL     3,314,500,858   
5              ST         NG                    GAS       426,092,142   
...           ...        ...                    ...               ...   
5288           ST         NG                    GAS        34,336,114   
5289           ST        TDF                    MSW           210,989   
5290           ST        RFO                    PET           343,852   
5291           ST        SUB                   COAL     1,738,032,266   
5292           ST        DFO                    PET         3,199,640   

                         Unnamed: 9  ...  \
0     Useful Thermal Output (MMBtu)  ...   
2                                 0  ...   
3                                 0  ...   
4                                 0  ...   
5                                 0  ...   
...                             ...  ...   
5288                        909,027  ...   
5289                          4,370  ...   
5290                          8,593  ...   
5291                              0  ...   
5292                              0  ...   

                                           Unnamed: 11  \
0     Fuel Consumption for Electric Generation (MMBtu)   
2                                              805,220   
3                                           56,641,702   
4                                           33,612,334   
5                                            4,423,555   
...                                                ...   
5288                                           178,558   
5289                                             1,101   
5290                                             1,790   
5291                                        20,742,815   
5292                                            38,062   

                                            Unnamed: 12  \
0     \n Fuel Consumption for Useful Thermal Output ...   
2                                                     0   
3                                                     0   
4       

In [ ]:
data.columns

Index(['2022 Carbon Dioxide Emissions at Electric Power Plants', 'Unnamed: 1',
       'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6',
       'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11',
       'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15',
       'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19',
       'Unnamed: 20'],
      dtype='object')

In [ ]:
data['embeddings'] = data['Unnamed: 1'].apply(lambda x: embedder.encode(x))

<ipython-input-23-0ddb6f499666>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['embeddings'] = data['Unnamed: 1'].apply(lambda x: embedder.encode(x))


In [ ]:
data

2022 Carbon Dioxide Emissions at Electric Power Plants  \
0                                            Plant Code       
2                                                     3       
3                                                     3       
4                                                     3       
5                                                     3       
...                                                 ...       
5288                                              99999       
5289                                              99999       
5290                                              99999       
5291                                              99999       
5292                                              99999       

                     Unnamed: 1 Unnamed: 2      Unnamed: 3   Unnamed: 4  \
0                    Plant Name      State    Sector Group  Sector Code   
2                         Barry         AL  ELECTRIC POWER            1   
3                         Barry         AL  ELECTRIC POWER            1   
4                         Barry         AL  ELECTRIC POWER            1   
5                         Barry         AL  ELECTRIC POWER            1   
...                         ...        ...             ...          ...   
5288  Estimate for Missing Data         WI      INDUSTRIAL            7   
5289  Estimate for Missing Data         WI      INDUSTRIAL            7   
5290  Estimate for Missing Data         WI      INDUSTRIAL            7   
5291  Estimate for Missing Data         WY  ELECTRIC POWER            1   
5292  Estimate for Missing Data         WY  ELECTRIC POWER            1   

       Unnamed: 5 Unnamed: 6             Unnamed: 7        Unnamed: 8  \
0     Prime Mover  Fuel Code  Aggregated Fuel Group  Generation (kWh)   
2              CA         NG                    GAS     2,817,683,000   
3              CT         NG                    GAS     5,336,143,000   
4              ST        BIT                   COAL     3,314,500,858   
5              ST         NG                    GAS       426,092,142   
...           ...        ...                    ...               ...   
5288           ST         NG                    GAS        34,336,114   
5289           ST        TDF                    MSW           210,989   
5290           ST        RFO                    PET           343,852   
5291           ST        SUB                   COAL     1,738,032,266   
5292           ST        DFO                    PET         3,199,640   

                         Unnamed: 9  ...  \
0     Useful Thermal Output (MMBtu)  ...   
2                                 0  ...   
3                                 0  ...   
4                                 0  ...   
5                                 0  ...   
...                             ...  ...   
5288                        909,027  ...   
5289                          4,370  ...   
5290                          8,593  ...   
5291                              0  ...   
5292                              0  ...   

                                            Unnamed: 12  \
0     \n Fuel Consumption for Useful Thermal Output ...   
2                                                     0   
3                                                     0   
4                                                     0   
5                                                     0   
...                                                 ...   
5288                                          1,336,804   
5289                                              6,426   
5290                                             12,637   
5291                                                  0   
5292                                                  0   

                    Unnamed: 13 Unnamed: 14            Unnamed: 15  \
0     Quantity of Fuel Consumed  Fuel Units  Tons of CO2 Emissions   
2                       792,906         Mcf                 46,963   
3                    5

In [ ]:
import heapq

In [ ]:
input = "Humboldt Bay"

In [ ]:
heap = []

In [ ]:
embeddings = data['embeddings'].values

In [ ]:
names = data['Unnamed: 1'].values

In [ ]:
names

array(['Plant Name', 'Barry', 'Barry', ..., 'Estimate for Missing Data',
       'Estimate for Missing Data', 'Estimate for Missing Data'],
      dtype=object)

In [ ]:
testEmb = embedder.encode(input)

In [ ]:
def find_similar():
  for i in range(len(embeddings)):
    sim = cosine_similarity([testEmb], [embeddings[i]])
    heapq.heappush(heap, (sim, names[i]))

  return heapq.nlargest(20, heap)

In [ ]:
test = find_similar()

ValueError: setting an array element with a sequence.

In [ ]:
test

[(array([[1.0000004]], dtype=float32), 'Humboldt Bay'),
 (array([[1.0000004]], dtype=float32), 'Humboldt Bay'),
 (array([[1.0000004]], dtype=float32), 'Humboldt Bay'),
 (array([[1.0000004]], dtype=float32), 'Humboldt Bay'),
 (array([[1.0000004]], dtype=float32), 'Humboldt Bay'),
 (array([[1.0000004]], dtype=float32), 'Humboldt Bay'),
 (array([[0.95664525]], dtype=float32), 'Watertown Power Plant'),
 (array([[0.90396345]], dtype=float32), 'Humboldt Bay'),
 (array([[0.90396345]], dtype=float32), 'Humboldt Bay'),
 (array([[0.863659]], dtype=float32), 'H Wilson Sundt Generating Station'),
 (array([[0.863659]], dtype=float32), 'H Wilson Sundt Generating Station'),
 (array([[0.863659]], dtype=float32), 'H Wilson Sundt Generating Station'),
 (array([[0.8196641]], dtype=float32), 'Water Treatment Plant Generators'),
 (array([[0.80261546]], dtype=float32), 'Humboldt Sawmill Company'),
 (array([[0.7971214]], dtype=float32), 'H Wilson Sundt Generating Station'),
 (array([[0.7971214]], dtype=float

In [ ]:
import sklearn
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
v = CountVectorizer()

In [ ]:
v.fit(data['Unnamed: 1'])

CountVectorizer()

In [ ]:
data['tokenized'] = data['Unnamed: 1'].apply(lambda x: v.transform([x]).toarray()[0])

<ipython-input-131-82d21f24761f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['tokenized'] = data['Unnamed: 1'].apply(lambda x: v.transform([x]).toarray()[0])


In [ ]:
data['tokenized']

0       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
2       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
3       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
4       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
                              ...                        
5288    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5289    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5290    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5291    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
5292    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...
Name: tokenized, Length: 5056, dtype: object

In [ ]:
tokens = data['tokenized'].values
type(tokens)

numpy.ndarray

In [ ]:
tokens

array([array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]),
       array([0, 0, 0, ..., 0, 0, 0]), ...,
       array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]),
       array([0, 0, 0, ..., 0, 0, 0])], dtype=object)

In [ ]:
testToken = v.transform([input])

In [ ]:
import math
def time_optimal_find_similar(input):
    heap = []
    testToken = v.transform([input]).toarray()[0].reshape(1, -1)
    testEmb = embedder.encode(input)
    words = input.split()
    for i in range(len(tokens)):
        sim1 = cosine_similarity([testEmb], [embeddings[i]])
        add = 0
        mult = 1
        for word in words:
            if word in names[i]:
                add += 1 * mult
            mult = mult / 4
        sim2 = cosine_similarity(testToken, tokens[i].reshape(1, -1))
        heapq.heappush(heap, ((sim1 * 2.5) + add + (sim2 * 1.5), names[i]))

    return heapq.nlargest(50, heap)

In [ ]:
test = find_similar()

In [ ]:
test

[(array([[2.00000036]]), 'Humboldt Bay'),
 (array([[2.00000036]]), 'Humboldt Bay'),
 (array([[1.19474243]]), 'Humboldt Sawmill Company'),
 (array([[0.91208957]]), 'McKay Bay Facility'),
 (array([[0.90000051]]), 'Tiger Bay'),
 (array([[0.90000051]]), 'Tiger Bay'),
 (array([[0.89090097]]), 'Bay Front'),
 (array([[0.89090097]]), 'Bay Front'),
 (array([[0.80608244]]), 'FirstEnergy Bay Shore'),
 (array([[0.80608244]]), 'FirstEnergy Bay Shore'),
 (array([[0.80608244]]), 'FirstEnergy Bay Shore'),
 (array([[0.79016325]]), 'Naval Submarine Base Kings Bay'),
 (array([[0.65007943]]), 'Redwood Falls'),
 (array([[0.65007943]]), 'Redwood Falls'),
 (array([[0.60697195]]), 'Bay View Backup Power Facility'),
 (array([[0.60697195]]), 'Bay View Backup Power Facility'),
 (array([[0.60179214]]), 'Jamaica Bay Peaking'),
 (array([[0.60179214]]), 'Jamaica Bay Peaking'),
 (array([[0.58948723]]), 'Marathon Bay Area Cogen'),
 (array([[0.58948723]]), 'Marathon Bay Area Cogen')]

In [ ]:
test = time_optimal_find_similar("Village Creek")

In [ ]:
test

[(array([[4.17699221]]), 'Village Creek Water Reclamation Facility'),
 (array([[3.28273106]]), 'Campbell Village'),
 (array([[2.47974992]]), 'Lagoon Creek'),
 (array([[2.47974992]]), 'Lagoon Creek'),
 (array([[2.47974992]]), 'Lagoon Creek'),
 (array([[2.47974992]]), 'Lagoon Creek'),
 (array([[2.3770175]]), 'Prairie Creek'),
 (array([[2.3770175]]), 'Prairie Creek'),
 (array([[2.35445595]]), 'Clifty Creek'),
 (array([[2.35445595]]), 'Clifty Creek'),
 (array([[2.35445595]]), 'Clifty Creek'),
 (array([[2.34813714]]), 'Kyger Creek'),
 (array([[2.34813714]]), 'Kyger Creek'),
 (array([[2.34813714]]), 'Kyger Creek'),
 (array([[2.34703732]]), 'Flint Creek'),
 (array([[2.34703732]]), 'Flint Creek'),
 (array([[2.32662562]]), 'TalenEnergy Martins Creek'),
 (array([[2.32662562]]), 'TalenEnergy Martins Creek'),
 (array([[2.32662562]]), 'TalenEnergy Martins Creek'),
 (array([[2.32662562]]), 'TalenEnergy Martins Creek')]

In [ ]:
test = find_similar("Power Barry")

Power


In [ ]:
test

[(array([[3.27769494]]), 'Power Island'),
 (array([[3.27641897]]), 'Barry'),
 (array([[3.27641897]]), 'Barry'),
 (array([[3.27641897]]), 'Barry'),
 (array([[3.27641897]]), 'Barry'),
 (array([[3.19578767]]), 'Millennium Power'),
 (array([[3.19578767]]), 'Millennium Power'),
 (array([[3.15939784]]), 'HL Power'),
 (array([[3.07320336]]), 'Freedom Power Project'),
 (array([[3.06250381]]), 'Birdsboro Power'),
 (array([[3.02630591]]), 'Redding Power'),
 (array([[3.02630591]]), 'Redding Power'),
 (array([[3.02630591]]), 'Redding Power'),
 (array([[3.00818443]]), 'Power Station 4'),
 (array([[3.00818443]]), 'Power Station 4'),
 (array([[2.99341444]]), 'Gavin Power, LLC'),
 (array([[2.99341444]]), 'Gavin Power, LLC'),
 (array([[2.95928625]]), 'Waterford Power, LLC'),
 (array([[2.95928625]]), 'Waterford Power, LLC'),
 (array([[2.95607114]]), 'Dickerson Power')]